### ISSUE TITLE
支持winform?

### ISSUE THREAD

**Issue by yuessir** [eagleboost/BeginInvokeToAsyncAwaitApp#1]
支持winform嗎?
Controls.BeginInvoke();
  public IAsyncResult BeginInvoke(Delegate method) => this.BeginInvoke(method, (object[]) null);

**Comment by eagleboost** [comment]
把OnCompleted里面对_dispatcher.InvokeAsync的调用改成Control.BeginInvoke试试看，不过Cancellation没法支持。

    public void OnCompleted(Action continuation)
    {
      _ctrl.BeginInvoke(continuation);
    }

    public bool CheckAccess()
    {
      return !_ctrl.InvokeRequired;
    }

    public void VerifyAccess()
    {
      if (_ctrl.InvokeRequired)
      {
        throw new InvalidOperationException();
      }
    }

**Comment by yuessir** [comment]
@eagleboost 照您的測試方式來驗證可否?

**Comment by eagleboost** [comment]
提交了一个简单实现供参考
https://github.com/eagleboost/BeginInvokeToAsyncAwaitApp/commit/191023316d6e77e8a7bb48e23d3fc7b5feafd8da
