### ISSUE TITLE
跨緒問題

### ISSUE THREAD

**Issue by yuessir** [eagleboost/BeginInvokeToAsyncAwaitApp#2]
在winform測試
增加一個label

在oncompleted
加入一個action
`
private Task DoSomethingUpdateAsync()
 {
            return Task.Run(async () =>
           {
               
               Print("Call DoSomethingUpdateAsync() on background");
             await  _waiter.WaitAsync();//執行後回到主緒
               label1.Text = "updating safe....";
           });
}
`
上面代碼沒問題

主要是移除
await  _waiter.WaitAsync();//執行後回到主緒
這拋跨緒錯誤

如果oncompleted開放給外部使用
Eg:  oncompleted( x=>DoSomethingUpdateAsync())
 但外部沒有加入await  _waiter.WaitAsync()
我該如何限制呢？

https://github.com/yuessir/BeginInvokeToAsyncAwaitApp/blob/f2d3d8a395434ddef50c8e4c3edb837cffac537c/WindowsFormsApp1/Form1.cs#L114

**Comment by eagleboost** [comment]
调用OnCompleted基本等同于调用Dispatcher.BeginInvoke，所以不再需要await _waiter.WaitAsync()了
